---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: debian-7.6

suites:
  - name: default
    run_list:
      - recipe[awesome::web]
      - recipe[awesome::source]
    attributes:
